### PR TITLE
feat: add env vars

### PR DESCRIPTION
**Pull request by Chr0my**
This PR allows setting custom environment variables inside the systemd service file.
It could be needed for specific things, like the elastic APM tracing.
i.e : 
```   
env_vars          => ["ELASTIC_APM_SERVER_URL=http://apm-server.domain:8200",
                               "ELASTIC_APM_GLOBAL_LABELS=label1=labelvalue1,label2=labelvalue2]
```                          
Generates : 
```
 [Service]
-
+Environment=ELASTIC_APM_SERVER_URL=http://apm-server.domain:8200
+Environment=ELASTIC_APM_GLOBAL_LABELS=label1=labelvalue1,label2=labelvalue2
```

### CODE REVIEW

**Comment by Chr0my** [comment]
@syberalexis Do you have a bit of time for this ? The pipeline is failing because a stdlib dependency that is below the one required for prometheus module if I'm not wrong.
`puppetlabs-stdlib, installed: 6.6.0, expected: >= 9.0.0 < 10.0.0`

**Comment by syberalexis** [comment]
Hello,

It's good for me.
I will try to finish to fix the CI next week ;)
Sorry for the late answer, my life is very busy.

**Comment by Chr0my** [comment]
Awesome, thanks a lot for your time 🙏

**Comment by syberalexis** [comment]
Sorry, i forgot to release…
I try to do it this evening.

**Pull request merged**
