### PR TITLE
Feat/support 0.26.0

### PR DESCRIPTION
**Pull request by Chr0my**
Fixes https://github.com/syberalexis/puppet-thanos/issues/31
* Rename `stores` to `endpoints`
* Remove old flags `receive.connection-pool-size` and `receive.connection-pool-size-per-host`
* Allow modifying `max_open_files`

### CODE REVIEW

**Comment by syberalexis** [comment]
Thank you for your great quality contribution.
I see Travis CI don’t work anymore, I try to see and fix that this evening and do the review ;)

**Comment by Chr0my** [comment]
Thanks for your update, I'm still working on fixing the ci

**Comment by syberalexis** [comment]
Can you just execute puppet strings command to generate an updated REFERENCE.MD file with your changes, please.
`puppet strings generate --format markdown`.

**Comment by Chr0my** [comment]
Just pushed it, the diff is pretty huge, tell me if it's ok for you

**Pull request merged**
